version: '3'

services:

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql-wjcrypto
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

    environment: 
      - MYSQL_DATABASE=wjcrypto
      - MYSQL_USER=wj
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - default

volumes:
  db_data: